### ISSUE TITLE
Functional Stateless React Components

### ISSUE THREAD

**Issue by andkhong** [riceball1/simple-code#25]
Your code is good; however, there are a lot of stateless components. Your style can be improved if you review the link below. Experienced React developers can instantly recognize the type of component if its stateless.

https://github.com/airbnb/javascript/tree/master/react#class-vs-reactcreateclass-vs-stateless

**Comment by riceball1** [comment]
I think there's a debate as to which is the best practice for using stateless vs non-stateless components. In terms of what I've been taught it seems that it's best to create reusable stateless components, but when necessary for state use a higher-order component. Thanks for the thought on this!
