### ISSUE TITLE
Reducers readibility

### ISSUE THREAD

**Issue by andkhong** [riceball1/simple-code#26]
Reducers are normally written with switch statements. Less bytes on the script, easy readability, more coding!

Furthermore, look into switch vs if-else patterns. There's a major difference between the two in terms of performance.

http://redux.js.org/docs/basics/Reducers.html

**Comment by riceball1** [comment]
True, I think in terms of performance for a small app it is not as significant. According to this [stackoverflow QA](https://stackoverflow.com/questions/767821/is-else-if-faster-than-switch-case), a switch would be best for more than 5 items. I'll consider this next time I'm setting up a larger application. Thanks!
