### ISSUE TITLE
Server API/Auth.js Modularity

### ISSUE THREAD

**Issue by andkhong** [riceball1/simple-code#27]
The point of middleware is the intercept Response-Request cycle. Not only that, it is also convenient for it's modularity. 

e.g. 

app.get('/', middleware1, middleware2, middleware3, ... etc...);

function middleware1(req, res, next){
  // chunk of code
 next();
}

function middleware2(req, res, next){
 // chunk of code
 next();
}

function middleware3(req, res, next){
// chunk of code
 res.end();
}

whereas ....

app.get('/,' function(req, res){
 // chunk of code 1
 // chunk of code 2
 // chunk of code 3
});

Which is easier to debug and maintain?

**Comment by riceball1** [comment]
Good point here, I will take a look at this issue
